variables:
  # Found through trial-and-error. May not be stable?
  ndk_home: /usr/local/lib/android/sdk/ndk-bundle 

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"  
      target: x86_64-unknown-linux-gnu          
    linux_32:
      imageName: "ubuntu-16.04"
      target: i686-unknown-linux-gnu             
    mac:
      imageName: "macos-10.13"
      target: x86_64-apple-darwin      
    windows:
      imageName: "vs2017-win2016"
      target: x86_64-pc-windows-msvc      
    windows_32:
      imageName: "vs2017-win2016"
      target: i686-pc-windows-msvc      
    android:
      imageName: "ubuntu-16.04"
      target: aarch64-linux-android   
      targetCapitalized: AARCH64-LINUX-ANDROID   
      arName: aarch64-linux-android-ar
      linkerName: aarch64-linux-android28-clang
      ignore_examples: True
    android_32:
      imageName: "ubuntu-16.04"
      target: arm-linux-androideabi   
      arName: arm-linux-androideabi-ar
      linkerName: armv7a-linux-androideabi28-clang
      targetCapitalized: ARM-LINUX-ANDROIDEABI   
      ignore_examples: True
    

pool:
  vmImage: $(imageName)

steps:
  - script:  |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install Rust (*NIX)
    condition: ne( variables['Agent.OS'], 'Windows_NT' ) 

  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain stable
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Install Rust (Windows)
    condition: eq( variables['Agent.OS'], 'Windows_NT' )

  - script: rustup target add $(target)
    displayName: Rustup add target

  - script: sudo apt-get install libpcsclite-dev
    displayName: Install libpsclite-dev (Linux only)
    condition: and( ne(variables['ignore_examples'], True), eq(variables['Agent.OS'], 'Linux'))

  - script: |
      echo "##vso[task.setvariable variable=CARGO_TARGET_$(targetCapitalized)_AR);]$(ndk_home)/toolchains/llvm/prebuilt/linux-x86_64/bin/$(arName)"
      echo "##vso[task.setvariable variable=CARGO_TARGET_$(targetCapitalized)_LINKER);]$(ndk_home)/toolchains/llvm/prebuilt/linux-x86_64/bin/$(linkerName)"
    displayName: Set Android Linker
    condition: contains( variables['target'], 'android' )

  - script: cargo build --all --target $(target)
    displayName: Cargo build

  - script: cargo build --examples --target $(target)
    displayName: Cargo build examples
    condition: ne( variables['ignore_examples'], True )

  - script: cargo test --all --target $(target)
    displayName: Cargo test